#!/bin/bash
## ipinfo [ipaddr...]
##
##      Get IP address info from ipinfo.io.  Address defaults to current.
##
## -- 
## Ronald E. Straight <straightre@gmail.com>

## @see http://ipinfo.io/developers/full-ip-details

## Bash script boilerplate variables.

declare -r    SCRIPT_NAME=$( basename "$0" ) ;

declare -r -i TRUE=1 FALSE=0 ;
declare -r -i RV_SUCCESS=0 RV_FAILURE=1  RV_NOOP=$RV_SUCCESS ;

declare -r    DEFAULT_SHORT_OPTS='hvn' DEFAULT_LONG_OPTS='help,verbose,dry-run,debug,trace' ;

declare    -i VERBOSITY=0 DRY_RUN=$FALSE VERBOSE=$FALSE DEBUG=$FALSE TRACE=$FALSE ;
declare       WHINGEE='' ;
declare       GFX_EM="$( tput setaf 1 2>/dev/null )" GFX_RS="$( tput sgr0 2 2>/dev/null )" ;

## Boilerplate functions.

function __isTrue()  { [[ $# -gt 0 ]] || return $RV_FAILURE ; declare value=$1 ; (( value > value/2 )) ; }
function __isEmpty() { [[ -z "$1" ]] ; } ;

function __isInt()   {
    declare str=${1?Missing required argument of string to be checked.} ;
    declare alt=${2:-NaN} ;

    ## @TODO(ronstra): Use `expr' and check for $? of 2?

    if [[ "$1" =~ ^-?[0-9]+$ ]] ; then
        echo $str ; return $RV_SUCCESS ;
    else
        echo $alt ; return $RV_FAILURE ;
    fi
} ;

function __Whinge()  { declare -i rv ; rv=$( __isInt "$1" ) && shift ; echo "[$( date +%Y-%m-%dT%H:%M:%S )]${WHINGEE:- }$@" 1>&2 ; return $rv ; }
function __Croak()   { __Whinge "$@" ; exit ; } ;

## Application variables.

declare -i HAS_DRY_RUN=$FALSE ;
declare    APP_OPTIONS='' ;

declare -r IPADDR_RE='^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' ;
declare -r CURL_EXE='curl' ;
declare -r IPINFO_URL_FMT='http://ipinfo.io/%s' ;

## Main logic.

unset -f __Main ; function __Main() {
    declare -a targets=( $@ ) ;
    declare    ipaddr url ;

    if (( ! $# )) ; then
        targets=( '' ) ;
    fi

    for ipaddr in "${targets[@]}" ; do
        if [[ "$ipaddr" ]] && [[ ! $ipaddr =~ $IPADDR_RE ]] ; then
            __Whinge "Malformed IP address '$ipspec'." ;
            continue ;
        fi

        url=$( printf "$IPINFO_URL_FMT" "$ipaddr" ) ;

        __Whinge "# $CURL_EXE $url ..." ;
        $CURL_EXE "$url" ; echo ;
    done
} ;

## Runtime.

__Main "$@" ; unset -f __Main ;


