#!/bin/env perl

use strict;
use warnings;
use English qw( -no_match_vars );

use FileHandle;
use List::Util qw( shuffle );

my(@lines);

unshift(@ARGV, '-') unless @ARGV;

#if (@ARGV) {
#    my $fn = shift @ARGV;
#    my $fp = FileHandle->new($fn, 'r')
#        or die "Failed to open input `$fn': $OS_ERROR";
#    while (<$fp>) { s/#.*$//; s/^\s+//; s/\s+$//; push(@lines, $ARG); }
#    $fp->close;
#}
#else {
    while (<>) { s/#.*$//; s/^\s+//; s/\s+$//; push(@lines, $ARG); }
#}

print join("\n", shuffle(@lines)) . "\n";

