#!/bin/sh
# Shell script to start Vim with less.vim.
# rstraight <2014-03-21> Always read from stdin.

#if test $# = 0; then
cmd="vim -c 'let no_plugin_maps = 1' -c 'runtime! macros/less.vim' $@ "
#echo $cmd
vim -c 'let no_plugin_maps = 1' -c 'runtime! macros/less.vim' $@ -
#else
#  vim --cmd 'let no_plugin_maps = 1' -c 'runtime! macros/less.vim' "$@"
#fi
