#!/bin/bash

XTERMSDIR="$HOME/bin/xterms.d"
SELECTION=$( find $XTERMSDIR -maxdepth 1 -type f -not -name '*.*' -and -not -name 'XX-*' -printf '%f\n'  |  zenity --width=320 --height=320 --list  --column='Where do you want to go today?' )

CMDLINE=$( grep -E '^Exec=' $XTERMSDIR/$SELECTION | awk -F= '{ print $2 }' )

$CMDLINE &
