#!/bin/bash

#eval $( ssh-agent )
#ssh-add

XTERM_EXE=x-terminal-emulator

#XTERM_LAUNCH_DIR="$HOME/.x-terminal-emulator"
##### USE ABOVE INSTEAD WHEN LOGGING IS ENABLED TO AVOID
##### CLUTTERING YOUR HOME DIRECTORY!
XTERM_LAUNCH_DIR="$HOME"

[[ -f "$HOME/.Xdefaults" ]] && xrdb $HOME/.Xdefaults

XTERM_ARGS=""
## -aw This option indicates that auto-wraparound should be allowed.  This allows the cursor to automatically wrap to the beginning of the
## next line when it is at the rightmost position of a line and text is output.
XTERM_ARGS="${XTERM_ARGS} -aw"

## -l Turn  logging  on.   Normally logging is not supported, due to security concerns.  Some versions of xterm may have logging enabled.
## The logfile is written to the directory from which xterm is invoked.
##XTERM_ARGS="${XTERM_ARGS} -l"

# -lc Turn on support of various encodings according to users locale setting, i.e., LC_ALL, LC_CTYPE, or LANG environment variables.
# This  is  achieved  by  turning on UTF-8 mode and by invoking luit for conversion between locale encodings and UTF-8.  (luit is not
# invoked in UTF-8 locales.)  This corresponds to the locale resource.
XTERM_ARGS="${XTERM_ARGS} -lc"

## +nul    This option enables the display of underlining.
#XTERM_ARGS="${XTERM_ARGS} +nul"

## -pc     This option enables the PC-style use of bold colors (see boldColors resource).
#XTERM_ARGS="${XTERM_ARGS} -pc"

## +rvc    This option enables the display of characters with reverse attribute as color.
#XTERM_ARGS="${XTERM_ARGS} +rvc"

## -rw     This option indicates that reverse-wraparound should be allowed.
## This allows the cursor to back up from the leftmost column of one line to the
## rightmost column of the previous line.  This is very useful for editing long
## shell command  lines  and  is  encouraged.  This option can be turned on and
## off from the "VT Options" menu.
#XTERM_ARGS="${XTERM_ARGS} -rw"

##       +sb     This option indicates that a scrollbar should not be displayed.
XTERM_ARGS="${XTERM_ARGS} +sb"

##       +sf     This option indicates that the standard escape codes should be generated for function keys.
#XTERM_ARGS="${XTERM_ARGS} +sf"

##       -si     This option indicates that output to a window should not automatically reposition the screen to the bottom of the scrolling region.  This option can be turned on and off from the "VT Options" menu.
XTERM_ARGS="${XTERM_ARGS} -si"

##     -sk     This  option indicates that pressing a key while using the scrollbar to review previous lines of text should cause the window to be repositioned automatically in the normal position at the bottom of the scroll region.
XTERM_ARGS="${XTERM_ARGS} -sk"

##       -sl number This option specifies the number of lines to save that have been scrolled off the top of the screen.  This corresponds to the save- Lines resource.  The default is "64".
XTERM_ARGS="${XTERM_ARGS} -sl 65536"

##       +sp     This option indicates that the standard escape codes should be generated for keypad and function keys.
XTERM_ARGS="${XTERM_ARGS} +sp"

##       +t      This option indicates that xterm should start in VT102 mode.
#XTERM_ARGS="${XTERM_ARGS} +t"

##       -tb     This  option,  corresponding  to the toolBar resource, indicates that xterm should display a toolbar (or menubar) at the top of its window.  The buttons in the toolbar correspond to the popup menus, e.g., control/left/mouse for "Main Options".
## NOTE :: This turns on Tektronix mode.
#XTERM_ARGS="${XTERM_ARGS} -tb"

## -ti term_id Specify the name used by xterm to select the correct response to
## terminal ID queries.  It also specifies the emulation level,  used to determine
## the type of response to a DA control sequence.  Valid values include vt52,
## vt100, vt101, vt102, and vt220 (the "vt" is optional).  The default is "vt100".
## The term_id argument specifies the terminal ID to use.  (This is the same as
## the decTerminalID resource).
#XTERM_ARGS="${XTERM_ARGS} -ti vt102"

## 	   -tm string This  option  specifies  a  series of terminal setting
## keywords followed by the characters that should be bound to those functions,
## similar to the stty program.  The keywords and their values are described in
## detail in the ttyModes resource.
#XTERM_ARGS="${XTERM_ARGS} -tm ..."

## 	   -tn name This option specifies the name of the terminal type to be set
## in the TERM environment variable.  It  corresponds  to  the  termName resource.
## This terminal type must exist in the terminal database (termcap or terminfo,
## depending on how xterm is built) and should have li# and co# entries.  If the
## terminal type is not found, xterm uses the built-in list "xterm", "vt102", etc. 
#XTERM_ARGS="${XTERM_ARGS} -tn vt102"

##       -uc     This option makes the cursor underlined instead of a box.
#XTERM_ARGS="${XTERM_ARGS} -uc"
## Really hard to see an underline-cursor in vim et al.

## 	   +ulit   This option, corresponding to the italicULMode resource, enables
## the display of characters  with  underline  attribute  as  italics rather than
## with underlining.
XTERM_ARGS="${XTERM_ARGS} +ulit"

## 	   -wf     This option indicates that xterm should wait for the window to
## be mapped the first time before starting the subprocess so that  the initial
## terminal  size settings and environment variables are correct.  It is the
## application's responsibility to catch subsequent terminal size changes.
#XTERM_ARGS="${XTERM_ARGS} -wf"

## 	   -xrm resourcestring This option specifies a resource string to be used.
## This is especially useful for setting resources that do not have separate com-
## mand line options:
## The program understands all of the core X Toolkit resource names and
## classes.  Application specific resources (e.g., "XTerm.NAME") follow:
#XTERM_ARGS="${XTERM_ARGS} -xrm 'keyboardType: tcap'"
#XTERM_ARGS="${XTERM_ARGS} -xrm 'backarrowKeyIsErase: false'"
XTERM_ARGS="${XTERM_ARGS} -xrm 'appkeypadDefault: false'"
#XTERM_ARGS="${XTERM_ARGS} -xrm 'curses: true'"
XTERM_ARGS="${XTERM_ARGS} -xrm 'cutNewline: false'"
XTERM_ARGS="${XTERM_ARGS} -xrm 'eightBitControl: true'"
XTERM_ARGS="${XTERM_ARGS} -xrm 'eightBitInput: true'"
XTERM_ARGS="${XTERM_ARGS} -xrm 'modifyCursorKeys: 0'"
XTERM_ARGS="${XTERM_ARGS} -xrm 'numLock: true'"
#XTERM_ARGS="${XTERM_ARGS} -xrm 'openIm: true'"
#XTERM_ARGS="${XTERM_ARGS} -xrm 'on5Clicks: all'" ## word, line, group, page, all, regex, none
#XTERM_ARGS="${XTERM_ARGS} -xrm 'trimSelection: true'"
XTERM_ARGS="${XTERM_ARGS} -xrm 'vt100Graphics: true'"
#XTERM_ARGS="${XTERM_ARGS} -xrm 'set-appkeypad(off)'"



CMDLINE="cd $XTERM_LAUNCH_DIR ; nohup $XTERM_EXE $XTERM_ARGS &> /dev/null &"
echo -e "\n$CMDLINE\n\n" > /dev/stderr
#read -p "[ENTER] "

eval $CMDLINE






